apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-app
  labels:
    app: iot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-app
  template:
    metadata:
      name: iot-app
      labels:
        app: iot-app
    spec:
      containers:
        - name: iot-app
          image: wil42/playground:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
              protocol: TCP
      restartPolicy: Always
